### ISSUE TITLE
Tomcat server

### ISSUE THREAD

**Issue by Shaheer4636** [hkhcoder/vprofile-project#41]
I have added all vprofile-2.war to /var/lib/tomcat9/webapps/ROOT.war. But still the webapp is no accessible on the browser. Its giving 404 error.

**Comment by Shaheer4636** [comment]
@hkhcoder please review the issue. I have been trying since yesterday but all progress.

**Comment by Shaheer4636** [comment]
There are the logs of tomcat9, the java version is openjdk 11.0.23 2024-04-16


Jul 03 18:34:06 ip-172-31-87-137 tomcat9[7478]: Server startup in [18178] milliseconds
Jul 03 18:34:07 ip-172-31-87-137 tomcat9[7478]: Illegal access: this web application instance has been stopped already. Could not load []. The following stack trace is thr>
Jul 03 18:34:07 ip-172-31-87-137 tomcat9[7478]: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [].>
Jul 03 18:34:07 ip-172-31-87-137 tomcat9[7478]:     at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1427)
Jul 03 18:34:07 ip-172-31-87-137 tomcat9[7478]:     at org.apache.catalina.loader.WebappClassLoaderBase.getResource(WebappClassLoaderBase.java:1052)
Jul 03 18:34:07 ip-172-31-87-137 tomcat9[7478]:     at com.mysql.cj.jdbc.AbandonedConnectionCleanupThread.checkThreadContextClassLoader(AbandonedConnectionCleanupThread.ja>
Jul 03 18:34:07 ip-172-31-87-137 tomcat9[7478]:     at com.mysql.cj.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:90)
Jul 03 18:34:07 ip-172-31-87-137 tomcat9[7478]:     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Jul 03 18:34:07 ip-172-31-87-137 tomcat9[7478]:     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Jul 03 18:34:07 ip-172-31-87-137 tomcat9[7478]:     at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by amalkuriakose** [comment]
Facing the same issue.....

**Comment by amalkuriakose** [comment]
I was able to resolve the issue.

First I checked the /var/log/tomcat9/localhost.YYYY-MM-DD.log file.

In the file, I could see RMQ errors:

 Caused by: com.rabbitmq.client.AuthenticationFailureException: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.
                at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:342)
                at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:909)
                at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:859)
                at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1000)
                at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:355)

This is is because the RMQ user was not created.

I then created the use and restarted the server.

sudo rabbitmqctl add_user test test
sudo rabbitmqctl set_user_tags test administrator
sudo systemctl restart rabbitmq-server

Then restarted tomcat9 also.

After that I was able to see the login page.
